name: Publish

on:
  push:
    branches:
      - main
    # types:
    #   - closed

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'main'

      - name: Check a new tag
        id: tag
        run: |
          export TAG_VERSION=$(grep version pubspec.yaml |  awk -F  ': ' '{print $2}')
          echo "version=$TAG_VERSION" >> $GITHUB_OUTPUT
          echo $TAG_VERSION
          git tag $TAG_VERSION
          git push origin $TAG_VERSION

      - name: Create a Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag.outputs.version }}

      - name: "Checkout TIKI SDK Flutter"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout current tag
        run: |
          git checkout ${{ steps.tag.outputs.version }}

      # Add the rest of the steps for xcframeworks and aar here
